### ISSUE TITLE
Lazy loading not working

### ISSUE THREAD

**Issue by vonba** [coreyward/gatsby-plugin-sanity-image#15]
When using SanityImage I sometimes only get the blurry preview image and never the real image.
It seems to be the same or very similar issue as https://github.com/gatsbyjs/gatsby/issues/21932 which is closed with no solution.

To replicate please go to https://nifty-jepsen-2ac991.netlify.app and click "past projects" in the menu. On other pages lazy loading seems to work, but not on the past projects screen. Reloading the page triggers image loading. Same with manually removing the `loading="lazy"` attribute in dev tools.

Dependencies from package.json
```

    "@sanity/block-content-to-react": "^2.0.7",
    "babel-plugin-styled-components": "^1.12.0",
    "dotenv": "^9.0.0",
    "gatsby": "^3.4.1",
    "gatsby-image": "^3.9.0",
    "gatsby-plugin-anchor-links": "^1.2.1",
    "gatsby-plugin-image": "^1.4.1",
    "gatsby-plugin-manifest": "^3.4.0",
    "gatsby-plugin-react-helmet": "^4.4.0",
    "gatsby-plugin-sanity-image": "^0.8.0",
    "gatsby-plugin-sharp": "^3.4.2",
    "gatsby-plugin-sitemap": "^4.0.0",
    "gatsby-plugin-styled-components": "^4.4.0",
    "gatsby-source-filesystem": "^3.4.0",
    "gatsby-source-sanity": "^7.0.4",
    "gatsby-transformer-sharp": "^3.4.0",
    "normalize.css": "^8.0.1",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-helmet": "^6.1.0",
    "react-slick": "^0.28.1",
    "styled-components": "^5.3.0"

```

**Comment by coreyward** [comment]
This is covered in the README, though it might not be clear.

> **⚠️ Minor gotchas with deferred loading**
> SanityImage is relying on browser-native deferred image loading. This generally works fine in browsers that support it, but there are situations where the unloaded image is hidden or covered, resulting in the full image never loading.
>
> If this happens, you can override the styles set on the full-size image using the img[data-loading] selector. This image sits immediately adjacent to the spaceball image and has the following default styles while loading:
>
> ```css
> position: absolute;
> width: 10px !important; /* must be > 4px to be lazy loaded */
> height: 10px !important; /* must be > 4px to be lazy loaded */
> opacity: 0;
> zindex: -10;
> pointerevents: none;
> userselect: none;
> ```

If you inspect the DOM on your website you'll see that your `div.slick-list` element has `overflow: hidden` on it. Because of this, the full-size image we are trying to lazy-load is not visible in the viewport, so the browser never attempts to load it.

<img width="1250" alt="Screen Shot 2021-08-02 at 10 27 10 AM" src="https://user-images.githubusercontent.com/81224/127886228-e41acd47-c553-446b-92e9-19572b49f89f.png">
<img width="439" alt="Screen Shot 2021-08-02 at 10 23 34 AM" src="https://user-images.githubusercontent.com/81224/127886443-51d677ca-cbb1-45f2-9264-af93f348da15.png">

To resolve this, reposition the `img[data-loading]` element. For example, setting `bottom: -20px` should do the trick in this scenario.

**Comment by vonba** [comment]
Hi Corey! Thank you so much for your quick reply. Apologies for not spotting the note in the readme.
I am actually doing the exact same thing without issues on another site (Gatsby + Sanity + Slick), but with an earlier version.

> To resolve this, reposition the `img[data-loading]` element. For example, setting `bottom: -20px` should do the trick in this scenario.

Maybe I'm being slow, but I didn't actually understand the solution you mentioned. Hiding the preview image completely like this works, and I understand why:

```
.galleryImage {
    img {
      &:not([loading]) {
        display: none;
      }
    }
  }

```  

However positioning the image while loading (`&[data-loading]` in my example) does not seem to work and I don't actually understand why it would. Wouldn't the preview still be in front of it, causing the exact same problem?

If you have a second to clarify I would appreciate it and I'm sure for anyone else using the very popular Slick it would be helpful as well.

Thanks!

**Comment by coreyward** [comment]
The full-size image is outside of the bounds of `.slick-list` and therefore clipped. Instead of hiding the preview image, just use `bottom: -20px` to position the full-size image within the visible bounds of `.slick-list`. I.e.:

```css
.galleryImage {
  img[data-loading] {
    bottom: -20px;
  }
}
```

(note: your example is missing the `data-` prefix on the attribute)

This works because `img[data-loading]` already has `position: absolute` set and comes later in the DOM, so is therefore drawn above the preview image (which does not have `position: absolute` or `position: relative` set). Further, the `.slick-slide` ancestor has `position: relative` set, creating a new positioning context that matches the bounds of the `.slick-list` element. This means that setting `bottom: -20px` on `img[data-loading]` will position it 20px above the bottom of the `.slick-list` container, which is in the view. I tested this on your website before my initial response and it worked, but if you did not have success with it I'd love to know why or have a chance to diagnose myself.
