### ISSUE TITLE
Image from `_raw` data has wrongly shaped `asset` key

### ISSUE THREAD

**Issue by SimeonUnder2** [coreyward/gatsby-plugin-sanity-image#2]
...and throws a PropTypes error. We fixed this by 'cleaning' the `asset` key but it's not pretty!

When coming from `_raw` (used primarily to get content from a PortableText field you end up with more keys than the PropType is expecting.

**Comment by coreyward** [comment]
Can you share a sample object structure for the image you're getting? I don't normally resolve references in Portable Text fields, so I just get back `{ asset: { _ref: "…" } }`, which is supported by this line (no crop or hotspot gets applied in this case):

https://github.com/coreyward/gatsby-plugin-sanity-image/blob/4411c4edec50321006a58b86c4d139019c1b09a6/src/index.jsx#L45

But it sounds like you're maybe resolving references or otherwise getting back something very different. It may also be useful to share the type definition from the studio to understand what is happening. Thanks!

**Comment by coreyward** [comment]
@SimeonUnder2 I'm going to close this for now, but if you find that there's something awry feel free to reopen.
