### ISSUE TITLE
Placeholder not taking up full size

### ISSUE THREAD

**Issue by jonohewitt** [coreyward/gatsby-plugin-sanity-image#21]
Hi Corey, thanks for this plugin! 

I'm having an issue with the blurred image placeholder only taking up about a tiny 40x30px for a brief moment before the full image loads (>1000px). 

```
  query PortfolioArtworkTemplateQuery($id: String!) {
    artwork: sanityArtwork(id: { eq: $id }) {
      artworkImage {
        ...ImageWithPreview
        alt
        description
      }
...
```

```
import Image from "gatsby-plugin-sanity-image"

<Image
  {...artworkImage}
  width={1000}
  style={{
    maxHeight: "max(55vh, 350px)",
    maxWidth: "100%",
  }}
/>
```

```
"gatsby": "^4.1.0",
"gatsby-plugin-sanity-image": "^0.10.0",
"gatsby-source-sanity": "^7.1.0",
```

Have you come across this at all? Thanks a lot for any help.

**Comment by coreyward** [comment]
Since `SanityImage` doesn't style your images, I’m betting you just need to add `width: 100%;` (and possibly `display: block;` if you don‘t already have that set) to the image styles.

My approach is to set global styles for images like so:

```css
img {
  display: block;
  max-width: 100%;
}
```

Then, depending on the usage, if I want an image to fit a bounding box like your styles show, I would use [emotion](https://emotion.sh/) to style the image like so:

```
<SanityImage
  {...image}
  width={1000}
  css={{
    width: "100%",
    maxHeight: "max(55vh, 350px)",
    objectFit: "contain",
  }}
/>
```

This ensures the image isn‘t distorted or cropped. If you use `object-fit: cover` instead it also has the extra benefit that if you supplied `hotspot` data to to `SanityImage`, the center point will be respected.

**Comment by jonohewitt** [comment]
Thanks a lot for the quick and detailed reply! Adding `width: 100%` fixed the tiny placeholder issue. I'm still getting a little bit of resizing happening between the placeholder and the loaded image though:

https://user-images.githubusercontent.com/47791294/141316349-48480ce0-a0e7-40ff-b327-1446ce5f513d.mp4

This is with:
```
      <Image
        {...artworkImage}

        width={1000}
        style={{
          width: "100%",
          maxHeight: "max(55vh, 350px)",
          objectFit: "contain",
          objectPosition: "50% 50%",
        }}
      />
```

Do you have any idea what might be causing this?

**Comment by coreyward** [comment]
Is there a `crop` parameter in `artworkImage`? If so, that's likely the culprit—it's changing the aspect ratio of the final image relative to the original (the low-quality image preview is computed at upload time and does not adapt to the final aspect ratio). It's plausible that this is something gatsby-plugin-sanity-image could improve, but I think a potential workaround here would be to use `options={{ __experimentalAspectRatio: true }}`, which will set the `width` and `height` attributes on the `image` based on a _simplified_ computation of the final aspect ratio and specified `width`.

**Comment by jonohewitt** [comment]
Yes, `crop` is included in `artworkImage` via the `...ImageWithPreview` fragment but the value is null. I've just tried `__experimentalAspectRatio` but it didn't affect the slight resizing after loading finishes.

**Comment by coreyward** [comment]
Hmm, interesting! Do you have a link I can use to check this out myself? I don't think it's gatsby-plugin-sanity-image specific, but it would help to know what is happening.

**Comment by jonohewitt** [comment]
Absolutely, thanks a lot for having a look even if you don't think it's related to the plugin! The site is still in construction but the resizing can be seen on any of the portfolio artworks here: [https://preview.christinelawes.com/portfolio/flying-high/](https://preview.christinelawes.com/portfolio/flying-high/)

Most of the code for this page is here: [portfolioArtwork.tsx](https://github.com/jonohewitt/christine-lawes/blob/main/web/src/components/portfolioArtwork.tsx)
The GraphQL query is here: [portfolio-artwork.tsx](https://github.com/jonohewitt/christine-lawes/blob/main/web/src/templates/portfolio-artwork.tsx)

**Comment by coreyward** [comment]
Okay, so I figured out what is going on here. The styles for this image have the image _element_ sitting 800px wide with an automatic height constrained by the calculated value `max(55vh, 350px)`. In my case that’s about 362px tall. The styles are specifying that the __replaced object__ (the image data) be constrained to fit within these bounds, but follow the intrinsic aspect ratio of that data (this is how `object-fit: contain` works).

<img width="848" alt="Screen Shot 2021-11-14 at 1 58 12 PM" src="https://user-images.githubusercontent.com/81224/141696473-919fce32-54a8-42ff-abcb-67d762bf3b57.png">
 
The aspect ratio of the original image is 700:507 (1.38067061). Sanity resizes this down to fit within a 20x20 square, resulting in a preview image (`lqip`) that is 20x14, or an aspect ratio of 10:7 (1.42857143). As this image is slightly wider than the aspect ratio of the original, the height-constrained preview image displays somewhat wider than the original. Further, because the replaced content is being sized to fit within the bounds provided, the aspect ratio information provided by using `__experimentalAspectRatio: true` does not have an effect on the dimensions of the preview image replaced content.

<img width="389" alt="Screen Shot 2021-11-14 at 1 54 33 PM" src="https://user-images.githubusercontent.com/81224/141696998-4a7ceab5-a943-4a60-8626-cb66401d2ce9.png">

<img width="384" alt="Screen Shot 2021-11-14 at 1 55 23 PM" src="https://user-images.githubusercontent.com/81224/141696999-76773ea6-40cb-4e78-8983-b673ae1e7805.png">


If you wanted to resolve this while still maintaining a constrained height, you could either specify the width explicitly (e.g. `width: calc((max(55vh, 350px) / 507) * 700);` and drop `object-fit: contain` from the preview, or use `object-fit: cover;` in conjunction with automatic width and `__experimentalAspectRatio`.

**Comment by jonohewitt** [comment]
Thanks for having a look and the detailed explanation! That makes sense that the tiny preview wouldn't have the exact same aspect ratio as the full image. I really appreciate your time helping me with this. 

In case you're interested, to keep things responsive within my boundaries for width `min(800px, 90% of the body)` and height `max(55vh, 350px)` I ended up taking the `width: calc((max(55vh, 350px) / 507) * 700);` idea and going with:



```js
const aspectRatio: number = artworkImage.asset.metadata.dimensions.aspectRatio
```

```jsx

<Image
{...artworkImage}
width={800}
style={{
  display: "block",
  margin: "auto",
  width: `
  calc(
    min( 
      max(55vh, 350px) * ${aspectRatio},
      800px,
      90vw - var(--scrollbar-width)
    )  
  )`,
  height: `
  calc( 
    min(
      max(55vh, 350px) * ${aspectRatio},
      800px,
      90vw - var(--scrollbar-width)
    )
    / ${aspectRatio}
  )`,
}}
/>
```

I found that I had to specify the height as well to stop vertical resizing between the preview and loaded image. A bit complicated but it loads well!
