### ISSUE TITLE
lqip not inheriting full image attributes.

### ISSUE THREAD

**Issue by simonlagneaux** [coreyward/gatsby-plugin-sanity-image#4]
Plugin is amazing, so happy to be able to use good old images tags and not Gatsby ugly div/figure combo. Thank you!
I'm having issues with lqip not inheriting the image attributes like width and height, or css (like a position absolute). Any workarounds?

**Comment by coreyward** [comment]
Hmm, CSS styles via `className` prop should be getting passed into the low-quality preview image without any issue. Can you share your code and/or a reproduction (e.g. CodeSandbox)?

We don't set `width` and `height` attributes on either the preview or full-size image right now, though. This is something I'm considering, but it would mean it needs to work in 100% of use cases (hard) or opt-in like setting them via another prop (which would be repetitive in many cases, which is a poor experience). If you have thoughts, I'd love feedback and examples of how you're using these in real-world scenarios.

For now, if you rely on the element having dimensions to keep CLS low you can instead set the dimensions on a wrapper div and set the CSS on the image to `width: 100%; height 100%; object-fit: cover;` (sub `object-fit: contain;` where appropriate), just be sure to still pass reasonable `width` and `height` props to the image component so the `srcSet` has reasonably sized options.

**Comment by simonlagneaux** [comment]
The LQIP image appears stretched before the loaded image kicks in, almost as if it the LQIP is not picking up the crop dimensions.

Maybe you could only set width/height attributes if both width and height props are set, as that would mean the aspect ratio is very important?

**Comment by coreyward** [comment]
> The LQIP image appears stretched before the loaded image kicks in, almost as if it the LQIP is not picking up the crop dimensions.

The `lqip` (preview) data is generated by Sanity when the image is uploaded. It is not served as part of the image API, and thus doesn't support cropping or other transformations. You have a few options if you'd like to pursue this: 

- Option 1: Generate the data manually by generating the image URL with very small dimensions, converting it to base64, and passing it in instead of the data retrieved from GraphQL.
- Option 2: Use CSS to size the `lqip` image based on your target dimensions, either letting the image stretch or using `object-fit: cover`.

> Maybe you could only set width/height attributes if both width and height props are set, as that would mean the aspect ratio is very important?

The issue is that the `width` and `height` props alone are not sufficient to determine the final aspect ratio of the image (or its dimensions). It will vary based on other parameters applied, including the crop, fit mode*, `rect` settings, orientation, and pad settings. If we can account for all of these it should be possible to reliably determine the output dimensions and aspect ratio, but that work hasn't been done.

*[Due to this bug with the @sanity/image-url library](https://github.com/sanity-io/image-url/issues/32), specifying both `width` and `height` parameters results in a `rect` parameter being added to the URL erroneously, preventing `fit` modes from working correctly. This results in an image that will match the provided dimensions even when it should not. I'm reluctant to create mechanisms for determining the output size of the image that depend on buggy, off-spec behavior of the image-url library.

**Comment by simonlagneaux** [comment]
Thanks for the detailed response @coreyward!
I used [React Ratio](https://github.com/Stanko/react-ratio) to get a container with locked ratio around. Working now like a charm.
