### ISSUE TITLE
React issue with htmlWidth and htmlHeight

### ISSUE THREAD

**Issue by dumle11** [coreyward/gatsby-plugin-sanity-image#42]
Hi, I am using the plugin to pull images to our website and then I am adding htmlWidth and htmlHeight props, to satisfy Google Lighthouse Pagespeed. 

It looks like everything is working when I run Gatsby in production/build context, but when I run Gatsby in develop mode, I am seeing error inside console, while the functionality is still working:

![image](https://user-images.githubusercontent.com/23082152/233042811-16402ec4-51e9-455a-a492-6259fd0c7946.png)

Issue I am seeing:
> ad-export-handler-for-browser.js:72 Warning: React does not recognize the `htmlWidth` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `htmlwidth` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
 
![image](https://user-images.githubusercontent.com/23082152/233043065-b8d27067-bd3c-4c55-9b83-3b38302b9a1a.png)

This makes me think there could be some issue with the plugin?

Using react 18.2.0, gatsby 5.6.1, gatsby-plugin-sanity-image 0.13.4

Thanks!

**Comment by coreyward** [comment]
Oh, yeah, doesn't look like `htmlWidth` and `htmlHeight` are ever removed from the `props` object before it's passed to `img`. Since it doesn't look like you're adjusting the orientation of the image via the configuration, you can simplify by just setting `options={{ __experimentalAspectRatio: true }}`, which will automatically compute and set the `width` and `height` attributes.
