### ISSUE TITLE
Custom onLoad function

### ISSUE THREAD

**Issue by tkatchenko** [coreyward/gatsby-plugin-sanity-image#6]
I was wondering if there's a clean way to implement a custom onLoad function? I have a carousel plugin that needs to be resized when the images have finished loading but overriding the `<Image />` onLoad attribute causes some strange behaviour, perhaps due to `loaded` never being set to true. Any help would be appreciated, it's a great component, thanks!

**Comment by coreyward** [comment]
The `ImageWithPreview` version of things uses the native browser lazy loading, which probably won't work well in a carousel. You might want to opt out of using the preview images altogether given this and using the default `<img>` tag with your own `onLoad` function, or otherwise trying to ascertain the final dimensions based on the viewport + styles + original image dimensions and crop parameters. 

This said, I'm open to checking for an `onLoad` prop (or `onPostLoad`?) and calling it from the intrinsic `onLoad` function that is responsible for transitioning from the preview to the final image if that seems like a better approach for you. Let me know what you think.

**Comment by tkatchenko** [comment]
Thanks Corey, all great suggestions, the final ratio one especially. I'll probably go with the default `<img>` tag for now, no immediate need for an `onPostLoad` unless you can think of other use cases that would benefit!
