### ISSUE TITLE
Lighthouse keeps complaining about Properly size images

### ISSUE THREAD

**Issue by jephjohnson** [coreyward/gatsby-plugin-sanity-image#7]
LighoutOut flag:
```
...
Properly size images
0.25 s
Serve images that are appropriately-sized to save cellular data and improve load time. Learn more.
...
```

Figure.ts
```
....
<SanityImage 
     {...item.slides}
     width={item.slides.size ? item.slides.size : 1200}
     alt={item.slides.alt ? item.slides.alt : ''}
     style={{
       width: "100%",
       height: "100%",
       objectFit: "cover",
    }} 
 />
...
```

Html output:
```
...
`<img src="https://cdn.sanity.io/images/n4lnu0lw/production/7d17992e03c7a24d8344b89fa22a1942bd080b42-4000x2670.jpg?rect=0,1,4000,2667&amp;w=375&amp;h=250&amp;q=75&amp;fit=max&amp;auto=format" srcset="https://cdn.sanity.io/images/n4lnu0lw/production/7d17992e03c7a24d8344b89fa22a1942bd080b42-4000x2670.jpg?w=375&amp;q=75&amp;fit=max&amp;auto=format&amp;dpr=0.5 188w,https://cdn.sanity.io/images/n4lnu0lw/production/7d17992e03c7a24d8344b89fa22a1942bd080b42-4000x2670.jpg?w=375&amp;q=75&amp;fit=max&amp;auto=format&amp;dpr=0.75 281w,https://cdn.sanity.io/images/n4lnu0lw/production/7d17992e03c7a24d8344b89fa22a1942bd080b42-4000x2670.jpg?w=375&amp;q=75&amp;fit=max&amp;auto=format&amp;dpr=1 375w,https://cdn.sanity.io/images/n4lnu0lw/production/7d17992e03c7a24d8344b89fa22a1942bd080b42-4000x2670.jpg?w=375&amp;q=75&amp;fit=max&amp;auto=format&amp;dpr=1.5 563w,https://cdn.sanity.io/images/n4lnu0lw/production/7d17992e03c7a24d8344b89fa22a1942bd080b42-4000x2670.jpg?w=375&amp;q=75&amp;fit=max&amp;auto=format&amp;dpr=2 750w" loading="lazy" alt="" size="900" style="width:100%;height:100%;object-fit:cover" class="css-0">`
...
```

**Comment by coreyward** [comment]
Usually this warning is due to serving up images that are either incorrect dimensions (e.g. a 500px wide image that'll be rendered at 300 device pixels wide [i.e. 150px @ 2x DPI]) or have not been compressed. It looks like you're toggling between `item.slides.size` (which is `375` in this case) and `1200` for the width, but rendering all images out at what is ostensibly the same width (`100%`). If your container is 375px wide, this image should be fine, but you can optimize further by specifying a `sizes` attribute that tells the browser how wide the image will be rendered before it does any painting or layout work. If `item.slide.size` isn't set, perhaps before the browser renders, then you're going to have images that are significantly oversized (though again using `sizes` will help). 

By the way, you don't need the ternary operator for your `alt` prop—if it's `null` or `undefined` you can just pass it directly, and if it's possible for it to be `false` you can instead use a logical OR operator (e.g. `item.slides.alt || ""`).

**Comment by coreyward** [comment]
Hi Jeph, I'm going to close this out since I haven't heard back, but if you still need assistance feel free to reply, and if you still think there's something wrong with gatsby-plugin-sanity-image go ahead and re-open.
